import '../models/challenge_model.dart';
import '../models/ranking_model.dart';

class MockBank {
  static final List<ChallengeModel> challenges = [
    // 1: Linguagens
    ChallengeModel(
      id: 101,
      moduleId: 1,
      subject: 'Linguagens',
      difficulty: 1,
      question: 'Em "Ela tem um coração de ouro", qual figura de linguagem expressa uma comparação implícita?',
      optionA: 'Metonímia',
      optionB: 'Metáfora',
      optionC: 'Hipérbole',
      optionD: 'Eufemismo',
      correctAnswer: 'B',
      explanation: 'A metáfora consiste em uma comparação implícita sem conectivo formal.',
      xpReward: 50,
    ),
    ChallengeModel(
      id: 102,
      moduleId: 1,
      subject: 'Linguagens',
      difficulty: 2,
      question: 'Choose the sentence with the correct use of Present Perfect:',
      optionA: 'She has lived in Brazil since 2020.',
      optionB: 'She lived in Brazil since 2020.',
      optionC: 'She has live in Brazil since 2020.',
      optionD: 'She is living in Brazil since 2020.',
      correctAnswer: 'A',
      explanation: 'O Present Perfect ("has lived") é empregado com "since" para indicar ação contínua.',
      xpReward: 60,
    ),
    ChallengeModel(
      id: 103,
      moduleId: 1,
      subject: 'Linguagens',
      difficulty: 2,
      question: 'Na norma-padrão da língua portuguesa, assinale a oração com concordância verbal correta:',
      optionA: 'Fazem dois anos que não o vejo.',
      optionB: 'Faz dois anos que não o vejo.',
      optionC: 'Haviam muitos alunos na sala.',
      optionD: 'Houveram bastantes problemas.',
      correctAnswer: 'B',
      explanation: 'O verbo fazer indicando tempo transcorrido é impessoal e fica no singular.',
      xpReward: 70,
    ),

    // 2: Matemática
    ChallengeModel(
      id: 201,
      moduleId: 2,
      subject: 'Matemática',
      difficulty: 1,
      question: 'Se f(x) = 2x + 5, qual é o valor de f(4)?',
      optionA: '11',
      optionB: '13',
      optionC: '15',
      optionD: '8',
      correctAnswer: 'B',
      explanation: 'Substituindo x por 4: f(4) = 2(4) + 5 = 8 + 5 = 13.',
      xpReward: 50,
    ),
    ChallengeModel(
      id: 202,
      moduleId: 2,
      subject: 'Matemática',
      difficulty: 2,
      question: 'Qual é a probabilidade de lançar um dado não viciado de 6 faces e obter um número primo?',
      optionA: '1/6',
      optionB: '1/3',
      optionC: '1/2',
      optionD: '2/3',
      correctAnswer: 'C',
      explanation: 'Primos entre 1 e 6: {2, 3, 5}. 3 de 6 = 1/2 (50%).',
      xpReward: 60,
    ),
    ChallengeModel(
      id: 203,
      moduleId: 2,
      subject: 'Matemática',
      difficulty: 3,
      question: 'Um triângulo retângulo possui catetos medindo 6 cm e 8 cm. O comprimento da hipotenusa é:',
      optionA: '9 cm',
      optionB: '10 cm',
      optionC: '12 cm',
      optionD: '14 cm',
      correctAnswer: 'B',
      explanation: 'Pitágoras: a² = 6² + 8² = 36 + 64 = 100 => a = 10 cm.',
      xpReward: 75,
    ),

    // 3: Ciências da Natureza
    ChallengeModel(
      id: 301,
      moduleId: 3,
      subject: 'Ciências da Natureza',
      difficulty: 1,
      question: 'Qual organela celular eucarionte é a principal produtora de energia (ATP)?',
      optionA: 'Ribossomo',
      optionB: 'Complexo Golgiense',
      optionC: 'Mitocôndria',
      optionD: 'Lisossomo',
      correctAnswer: 'C',
      explanation: 'A mitocôndria realiza a fosforilação oxidativa que gera ATP.',
      xpReward: 50,
    ),
    ChallengeModel(
      id: 302,
      moduleId: 3,
      subject: 'Ciências da Natureza',
      difficulty: 2,
      question: 'Segundo a Segunda Lei de Newton (F = m · a), uma força de 40 N aplicada a um corpo de 8 kg resulta em:',
      optionA: '320 m/s²',
      optionB: '5 m/s²',
      optionC: '0,2 m/s²',
      optionD: '48 m/s²',
      correctAnswer: 'B',
      explanation: 'a = F / m = 40 / 8 = 5 m/s².',
      xpReward: 60,
    ),

    // 4: Ciências Humanas
    ChallengeModel(
      id: 401,
      moduleId: 4,
      subject: 'Ciências Humanas',
      difficulty: 1,
      question: 'A Lei nº 10.639/2003 alterou a LDB para tornar obrigatório nas escolas o ensino de:',
      optionA: 'Língua Latina clássica',
      optionB: 'História e Cultura Afro-Brasileira e Indígena',
      optionC: 'Economia Financeira',
      optionD: 'Constituição Internacional',
      correctAnswer: 'B',
      explanation: 'A Lei 10.639/03 valoriza o legado histórico e cultural do povo negro na formação nacional.',
      xpReward: 60,
    ),
    ChallengeModel(
      id: 402,
      moduleId: 4,
      subject: 'Ciências Humanas',
      difficulty: 2,
      question: 'O bioma característico do Maranhão que combina elementos de Cerrado, Caatinga e Amazônia é:',
      optionA: 'Mata Atlântica',
      optionB: 'Mata dos Cocais (ecótono de transição)',
      optionC: 'Pampa',
      optionD: 'Pantanal',
      correctAnswer: 'B',
      explanation: 'A Mata dos Cocais é uma zona ecológica de transição típica do Maranhão.',
      xpReward: 70,
    ),

    // 5: Atualidades
    ChallengeModel(
      id: 501,
      moduleId: 5,
      subject: 'Atualidades',
      difficulty: 1,
      question: 'O Acordo de Paris (2015) é um tratado internacional histórico cujo objetivo central é:',
      optionA: 'Limitar o aquecimento global bem abaixo de 2°C',
      optionB: 'Eliminar todo comércio de combustíveis',
      optionC: 'Substituir as moedas globais por criptoativos',
      optionD: 'Unificar as taxas aduaneiras mundiais',
      correctAnswer: 'A',
      explanation: 'O tratado visa frear o aumento da temperatura média do planeta reduzindo emissões.',
      xpReward: 50,
    ),
    ChallengeModel(
      id: 502,
      moduleId: 5,
      subject: 'Atualidades',
      difficulty: 2,
      question: 'A Lei Geral de Proteção de Dados (LGPD - Lei nº 13.709/2018) estabelece sobre dados de menores:',
      optionA: 'A comercialização para publicidade',
      optionB: 'O melhor interesse do menor e minimização de dados',
      optionC: 'A publicação obrigatória de notas na internet',
      optionD: 'A dispensa de segurança digital',
      correctAnswer: 'B',
      explanation: 'O Art. 14 da LGPD determina que o tratamento deve ocorrer no melhor interesse do jovem.',
      xpReward: 65,
    )
  ];

  static final List<RankingModel> ranking = [
    RankingModel(id: '1', name: 'Amberson Rogers', level: 6, xp: 1250, completedChallenges: 18),
    RankingModel(id: '2', name: 'Jhony Fernandes', level: 5, xp: 980, completedChallenges: 15),
    RankingModel(id: '3', name: 'Kelly Lorrany', level: 5, xp: 920, completedChallenges: 14),
    RankingModel(id: '4', name: 'Weldes Reis', level: 4, xp: 840, completedChallenges: 12),
    RankingModel(id: '5', name: 'Ana Beatriz Sousa', level: 4, xp: 760, completedChallenges: 11),
    RankingModel(id: '6', name: 'Lucas Gabriel Lima', level: 3, xp: 620, completedChallenges: 9),
  ];
}
