[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://backend-calm-sound-7047.fly.dev/api"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
